#lang racket
;; Generates ../resources/Racket.sublime-syntax from syntax_template.yaml.
;;
;; The template contains three placeholders that are replaced with regex
;; alternations of identifiers exported by the `racket` module:
;;
;;   __FORM_LIST__       syntactic forms (macros, core forms)
;;   __PROCEDURE_LIST__  identifiers bound to procedures
;;   __VALUE_LIST__      identifiers bound to non-procedure values
;;
;; Scribble.sublime-syntax is derived from the same rendered text: the header
;; is swapped, `main` becomes `racket-main`, and a new `main` treats the file
;; as prose containing @-expressions.
;;
;; Usage:  racket tools/gen_syntax.rkt

(require racket/runtime-path)

(define-runtime-path template-path "syntax_template.yaml")
(define-runtime-path output-path "../resources/Racket.sublime-syntax")
(define-runtime-path scribble-output-path "../resources/Scribble.sublime-syntax")

;; ---------------------------------------------------------------------------
;; Classifying the exports of `racket`

;; module->exports returns, for each of variables and syntax, an association
;; list from phase level to a list of (name origin ...) entries. Collect the
;; names from every phase into a set.
(define (export-names phase-alist)
  (for*/set ([(phase entries) (in-dict phase-alist)]
             [entry (in-list entries)])
    (car entry)))

(define (bound-to-procedure? name)
  ;; Syntax bindings cannot be evaluated as expressions; treat any failure
  ;; as "not a procedure".
  (with-handlers ([exn:fail? (λ (_) #f)])
    (procedure? (eval name))))

(define (classify-exports module-name)
  (parameterize ([current-namespace (make-base-empty-namespace)])
    (namespace-require module-name)
    (define-values (variables syntax) (module->exports module-name))
    (define variable-names (export-names variables))
    (define syntax-names (export-names syntax))
    (define procedure-names
      (for/set ([name (in-set (set-union variable-names syntax-names))]
                #:when (bound-to-procedure? name))
        name))
    (values (set-subtract syntax-names procedure-names)
            procedure-names
            (set-subtract variable-names syntax-names procedure-names))))

;; ---------------------------------------------------------------------------
;; Rendering

(define (regex-quote str)
  (regexp-replace* #px"[][(){}.*+?^$|\\\\#-]" str "\\\\&"))

;; Longest first so that the alternation prefers the longest match; ties
;; broken alphabetically so the output is deterministic.
(define (alternation names)
  (define strings
    (sort (set-map names symbol->string)
          (λ (a b)
            (or (> (string-length a) (string-length b))
                (and (= (string-length a) (string-length b)) (string<? a b))))))
  (string-append "(?:" (string-join (map regex-quote strings) "|") ")"))

(define generated-note
  (string-append
   "# [PACKAGE DEVELOPMENT NOTE]: This file is GENERATED by tools/gen_syntax.rkt\n"
   "# from tools/syntax_template.yaml\n"
   "# with identifier lists computed from the `racket` module. Edit the template,\n"
   "# then re-run:\n"
   "#     racket tools/gen_syntax.rkt\n"))

(define (with-generated-note template)
  (string-replace template "%YAML 1.2\n---\n" (string-append "%YAML 1.2\n---\n" generated-note) #:all? #f))

(define (render template forms procedures values)
  (for/fold ([text (with-generated-note template)])
            ([(placeholder names) (in-dict (list (cons "__FORM_LIST__" forms)
                                                 (cons "__PROCEDURE_LIST__" procedures)
                                                 (cons "__VALUE_LIST__" values)))])
    (string-replace text placeholder (alternation names))))

(define racket-header
  "name: Racket\nscope: source.racket\nversion: 2\nfile_extensions:\n  - rkt\n  - rktl\n  - rktd\nfirst_line_match: '^#lang\\b'\n")
(define scribble-header
  "name: Scribble\nscope: text.scribble\nversion: 2\nfile_extensions:\n  - scrbl\nfirst_line_match: '^#lang\\s+scribble'\n")
(define scribble-main
  "contexts:\n  main:\n    - include: lang-directive\n    - include: at-expression\n    # everything else is literal prose\n\n")

(define (scribble-syntax racket-syntax)
  (unless (string-contains? racket-syntax racket-header)
    (error 'gen_syntax "template header changed; update racket-header"))
  (let* ([text (string-replace racket-syntax racket-header scribble-header)]
         [text (string-replace text "include: main" "include: racket-main")]
         [text (string-replace text "\n  main:\n" "\n  racket-main:\n")]
         [text (string-replace text "contexts:\n" scribble-main #:all? #f)])
    text))

(define (write-file path text)
  (with-output-to-file path #:exists 'replace (λ () (void (write-string text))))
  (printf "Wrote ~a (~a bytes)\n" (simple-form-path path) (string-length text)))

(module+ main
  (define-values (forms procedures values) (classify-exports 'racket))
  (printf "~a forms, ~a procedures, ~a values\n"
          (set-count forms) (set-count procedures) (set-count values))
  (define output (render (file->string template-path) forms procedures values))
  (write-file output-path output)
  (write-file scribble-output-path (scribble-syntax output)))
